### ISSUE TITLE
关于增量更新时其他文件的下载

### ISSUE THREAD

**Issue by zhui22222** [tefuirZ/alist-strm#11]
再对一个文件夹进行增量更新时，虽然可以跳过已经下载过的文件，但是每个文件都会耗时几秒钟，如果这个目录文件数较多，每次增量更新耗费时间过长，能否改进判断机制，减少对已下载文件的判断时间？

**Comment by tefuirZ** [comment]
目前已下载文件的跳过不是已经优化过啦   在开始遍历alist下的文件时就开始跟本地目录树对比了  还是会比较慢吗

**Comment by zhui22222** [comment]
是不是您在循环里加了下载时间间隔的延迟，发现每判断一个文件就要等个两三秒再去处理下一个文件，比如我有1000个文件，新增了1个文件，处理完至少要2000多秒

**Comment by zhui22222** [comment]
> 目前已下载文件的跳过不是已经优化过啦 在开始遍历alist下的文件时就开始跟本地目录树对比了 还是会比较慢吗

不知道您什么时候优化的，我也是一两周前发现的，后面没再测试了

**Comment by tefuirZ** [comment]
> > 目前已下载文件的跳过不是已经优化过啦 在开始遍历alist下的文件时就开始跟本地目录树对比了 还是会比较慢吗
> 
> 不知道您什么时候优化的，我也是一两周前发现的，后面没再测试了

后面有更新啦  最新的版本号是6.0.5

**Comment by jqtmviyu** [comment]
> 再对一个文件夹进行增量更新时，虽然可以跳过已经下载过的文件，但是每个文件都会耗时几秒钟，如果这个目录文件数较多，每次增量更新耗费时间过长，能否改进判断机制，减少对已下载文件的判断时间？

我也遇到同样的问题, 看了下提交记录, 只需要修改 `创建strmの配置文件 -> 编辑 -> 下载文件时间间隔` 改成 `0-0`, 延迟就是取这两个范围的随机
