### ISSUE TITLE
PUID变量

### ISSUE THREAD

**Issue by gldl137** [tefuirZ/alist-strm#15]
docker能不增加PUID和PGID变量，好手动管理文件

**Comment by tefuirZ** [comment]
直接给777了呀 管理不了吗~

**Comment by gldl137** [comment]
给777，是可以管理，但我是用moviepilot自动管理的文件，emby删除文件，moviepilot自动也删除源文件。moviepilot和emby都设置PUID,我是unraid系统

**Comment by gldl137** [comment]
可以了
