### ISSUE TITLE
生成的strm文件为root权限

### ISSUE THREAD

**Issue by nigo81** [tefuirZ/alist-strm#5]
执行任务生成的strm为root权限，我想为普通用户的权限，因为我想用syncthing同步，而root文件不能同步。请问可以怎么设置吗？
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/dfc4ef94-5388-486c-b48a-c886246bc808">

**Comment by tefuirZ** [comment]
唔 这玩意儿还真没考虑过同步问题 默认是root是因为容器内部是root用户运行的 如果会运行Python的话可以用其他用户运行试试

**Comment by tefuirZ** [comment]
最新版本的已经将strm文件包括目录更改为777权限了
