### ISSUE TITLE
带有 emoji 的文件目录

### ISSUE THREAD

**Issue by QYQSDTC** [tefuirZ/alist-strm#6]
我想抓取小雅上🏷我的115 里的内容结果报错
```
ERROR - 脚本运行过程中发生错误: 'NoneType' object has no attribute 'get'
子进程结束，返回码: 1
```
最后我发现 🏷我的115 在 URL 后面多了几个字符
![CleanShot-9OzC3fWd@2x](https://github.com/user-attachments/assets/6d9a72cd-98ae-45e3-a187-917640c0fea1)

而🈴我的阿里分享就没问题
![CleanShot-KyqlvvLL@2x](https://github.com/user-attachments/assets/5ad79d5f-afae-47aa-84c5-02be4f23a001)

我在设置里试了 /🏷我的115 和 /🏷%EF%B8%8F我的115都报同一个错误

**Comment by tefuirZ** [comment]
这个后面尝试下把 因为我没有这个使用需求 到时候看看怎么处理  url编码可能会适配？  没这样干过 有个新版本 后续会推出 到时候看看
