### ISSUE TITLE
Windows 11下怎样使用？运行后提示：请提供配置ID作为命令行参数

### ISSUE THREAD

**Issue by truelove2017ye** [tefuirZ/alist-strm#7]
Windows 11下怎样使用？运行后提示：
"C:\Users\True Love\AppData\Local\Programs\Python\Python312\python.exe" D:\emby\alist-strm-3.0.1\main.py 
2024-09-18 19:23:24 - INFO - 脚本运行中。。。。。。。
2024-09-18 19:23:24 - ERROR - 请提供配置ID作为命令行参数

进程已结束，退出代码为 0

请指教，谢谢！

**Comment by truelove2017ye** [comment]
我是小白，windows运行app.py有很多错误，可能是我没有配置好，可不可以详细指导一下

**Comment by tefuirZ** [comment]
你是用什么运行的   编译器吗 还是直接使用命令行 就是主程序应该是app.py 然后它会启动web服务器 完事浏览器访问 http://127.0.0.1:5000  根据网页操作就好了
