### ISSUE TITLE
生成strm的实际位置不是配置中的目标目录

### ISSUE THREAD

**Issue by FEOQin** [tefuirZ/alist-strm#8]
`version: '3.8'

services:
  alist-strm:  
    image: itefuir/alist-strm:latest
    container_name: alist-strm
    hostname: alist-strm
    ports:
      - target: 5000
        published: "5000"
        protocol: tcp
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /DATA/AppData/aliststrm/volume1/video:/volume1/video
      - /DATA/AppData/aliststrm/congfig:/config
      - /media/devmon/Sd2/QB/Alist-strm:/app/cache
      - /media/devmon/Sd2/QB/Alist-strm:/Alist-strm        #目标目录1
      - /media/devmon/新加卷/Alist-strm:/Alist-strm         #目标目录2
    network_mode: bridge
`
查看配置文件日志内容：
![image](https://github.com/user-attachments/assets/4ab94ffe-6edd-4228-9491-323d43c1b5ec)
查看Files中没有文件：
![image](https://github.com/user-attachments/assets/ccca6f26-38eb-4e6f-b98b-28021d993778)
扫描整个系统找到生成strm的实际位置：
![image](https://github.com/user-attachments/assets/5bf31245-e592-468f-a51c-1d4e7f76bc32)

**Comment by tefuirZ** [comment]
你docker映射有问题
