### ISSUE TITLE
下载元数据失败

### ISSUE THREAD

**Issue by LGuangming** [tefuirZ/alist-strm#9]
看日志所有的元数据都下载失败，但我进入alist网页下载又可以直接下载

![image](https://github.com/user-attachments/assets/f8c46ea0-d667-4e46-8e74-1c35a04f8770)

**Comment by tefuirZ** [comment]
请自查alist是否开启了签名

**Comment by LGuangming** [comment]
> 请自查alist是否开启了签名  

确认挂载的云盘和别名都没有启用签名，元信息也没有开启
![image](https://github.com/user-attachments/assets/9179e463-bbfa-4e8f-8701-fbe497b9f94c)![image](https://github.com/user-attachments/assets/7ec58d52-3e79-45b6-a980-f5cc7b692057)![image](https://github.com/user-attachments/assets/5e118f5b-d760-4281-88d7-e16972ff30aa)![image](https://github.com/user-attachments/assets/8d812466-c121-409e-95cc-d195bfe08ce8)

**Comment by tefuirZ** [comment]
![Screenshot_20241018_003226](https://github.com/user-attachments/assets/ae83f325-63c3-4714-8b43-61e04ce41d38)
全局里面还有个签名设置哦  顺便去检查下strm里的链接是否正常

**Comment by LGuangming** [comment]
> ![Screenshot_20241018_003226](https://github.com/user-attachments/assets/ae83f325-63c3-4714-8b43-61e04ce41d38)
> 
> 全局里面还有个签名设置哦  顺便去检查下strm里的链接是否正常

看到了，签名真是无处不在，另外想问下，如果真的需要签名，之前可以填写API token，现在的版本在哪里可以填写token呢

**Comment by tefuirZ** [comment]
新版本不再支持签名了，这个是没有办法的事  介于保证脚本的速度以及存储的稳定性。只能选择使用alist的webdav，而webdav是不支持获取签名后缀的。如果使用alist的api来遍历目录，创建strm会导致某些存储被拦截甚至封号。。。
